domain/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.DomainListView.as_view(), name='domains'),
    path('add', views.DomainCreateView.as_view(), name='domain_create'),
    path('<int:domain_code>', views.DomainDetailView.as_view(), name='domain_detail'),
    path('<int:domain_code>/edit', views.DomainUpdateView.as_view(), name='domain_update'),
    path('<int:domain_code>/skill/add', views.SkillCreateView.as_view(), name='skill_create'),
    path('<int:domain_code>/skill/<int:skill_code>', views.SkillDetailView.as_view(), name='skill_detail'),
    path('<int:domain_code>/skill/<int:skill_code>/edit', views.SkillUpdateView.as_view(), name='skill_update'),
    path('<int:domain_code>/skill/<int:skill_code>/strategy/add',
         views.StrategyCreateView.as_view(), name='strategy_create'),
    path('<int:domain_code>/skill/<int:skill_code>/strategy/<int:strategy_code>',
         views.StrategyDetailView.as_view(), name='strategy_detail'),
    path('<int:domain_code>/skill/<int:skill_code>/strategy/<int:strategy_code>/edit',
         views.StrategyUpdateView.as_view(), name='strategy_update'),
]

graph/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.GraphListView.as_view(), name='graphs'),
    path('create', views.CreateGraph.as_view(), name='create_graph'),
    path('create/json', views.GraphFromJSONView.as_view(), name='graph_from_json'),
    path('graph/<int:pk>', views.GraphDetailView.as_view(), name='detail_graph'),
    path('graph/<int:pk>/topsort', views.TopSortView.as_view(), name='graph_topsort'),
    path('graph/<int:pk>/add_nullpoint', views.AddNullPointView.as_view(), name='graph_add_nullpoint'),
    path('graph/<int:pk>/json', views.GraphToJSONView.as_view(), name='graph_to_json'),
    path('graph/<int:pk>/add_vertex', views.AddVertexView.as_view(), name='add_vertex'),
    path('graph/<int:pk>/add_edge', views.AddEdgeView.as_view(), name='add_edge'),
    path('vertex/<int:pk>', views.VertexDetailView.as_view(), name='detail_vertex'),
    path('vertex/<int:pk>/add_incoming', views.AddIncomingEdgeView.as_view(), name='create_incoming'),
    path('vertex/<int:pk>/add_incoming_new', views.CreateIncomingView.as_view(), name='create_incoming_new'),
    path('vertex/<int:pk>/add_outcoming', views.AddOutcomingEdgeView.as_view(), name='create_outcoming'),
    path('vertex/<int:pk>/add_outcoming_new', views.CreateOutcomingView.as_view(), name='create_outcoming_new'),
    path('vertex/delete_incoming/<int:pk>', views.DeleteIncomingEdgeView.as_view(), name='delete_incoming'),
]

skillmap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html"), name='/'),
    path('graph/', include('graph.urls')),
    path('domain/', include('domain.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

domain/models.py
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver


class Domain(models.Model):
    code = models.IntegerField(unique=True)
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return "[%d] %s" % (self.code, self.name)


class Skill(models.Model):
    code = models.IntegerField()
    domain = models.ForeignKey(Domain, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return "[%d] %s" % (self.code, self.name)


class Strategy(models.Model):
    code = models.IntegerField()
    skill_goal = models.ForeignKey(Skill, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    problem = models.TextField(null=True, blank=True)

    def __str__(self):
        return "[%d] %s" % (self.code, self.name)


class Action(models.Model):
    strategy = models.ForeignKey(Strategy, on_delete=models.CASCADE)
    order = models.IntegerField()
    description = models.TextField()
    prerequisites = models.ManyToManyField(Strategy, through='Prerequisite', related_name='prerequisites')


class Prerequisite(models.Model):
    action = models.ForeignKey(Action, on_delete=models.CASCADE)
    strategy = models.ForeignKey(Strategy, on_delete=models.CASCADE)


@receiver(pre_save, sender=Domain)
def set_domain_code(sender, instance, **kwargs):
    if instance.pk is None:
        instance.code = max(Domain.objects.all().values_list('code', flat=True), default=0) + 1


@receiver(post_save, sender=Domain)
def set_plugs_in_domain(sender, instance, created, **kwargs):
    if created:
        Skill.objects.create(domain=instance,
                             code=0,
                             name="Заглушка")


@receiver(pre_save, sender=Skill)
def set_skill_code(sender, instance, **kwargs):
    if instance.pk is None:
        instance.code = max(Skill.objects.filter(domain=instance.domain).values_list('code', flat=True), default=0) + 1


@receiver(pre_save, sender=Strategy)
def set_strategy_code(sender, instance, **kwargs):
    if instance.pk is None:
        instance.code = max(Strategy.objects.filter(skill_goal=instance.skill_goal).values_list('code', flat=True),
                            default=0) + 1


@receiver(pre_save, sender=Action)
def set_action_order(sender, instance, **kwargs):
    if instance.pk is None:
        instance.order = max(Action.objects.filter(strategy=instance.strategy).values_list('order', flat=True),
                             default=0) + 1

domain/forms.py
from itertools import groupby

from django.contrib.admin.widgets import FilteredSelectMultiple
from django.forms import ModelForm
from django.forms.models import ModelChoiceIterator, inlineformset_factory

from domain.models import Strategy, Action, Domain


class StrategyIterator(ModelChoiceIterator):
    def __init__(self, domain_code, *args, **kwargs):
        #domain_code = kwargs.pop('domain_code', None)
        print("====================================================================")
        print(domain_code)
        print("====================================================================")
        self.queryset = Strategy.objects.filter(skill_goal__domain=Domain.objects.get(code=domain_code))
        super(StrategyIterator, self).__init__(*args, **kwargs)

    def __iter__(self):
        queryset = self.queryset.select_related('skill_goal').order_by('skill_goal__code', 'code')
        groups = groupby(queryset, key=lambda x: x.skill_goal)
        for skill_goal, strategies in groups:
            yield [
                skill_goal.name,
                [
                    (strategy.id, strategy.name)
                    for strategy in strategies
                ]
            ]


class ActionForm(ModelForm):
    class Meta:
        model = Action
        fields = ['order', 'description', 'prerequisites']
        widgets = {
            'prerequisites': FilteredSelectMultiple("verbose name", is_stacked=True, attrs={'size': 12})
        }

    def __init__(self, domain_code, *args, **kwargs):
        #domain_code = Domain.objects.get(code=kwargs.pop('domain_code', None))
        super(ActionForm, self).__init__(*args, **kwargs)
        self.fields['prerequisites'].choices = StrategyIterator(domain_code=domain_code, field=self.fields['prerequisites'])


ActionsFormSet = inlineformset_factory(Strategy, Action, form=ActionForm, extra=1)

domain/views.py
# Create your views here.
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView

from domain.forms import ActionsFormSet
from domain.models import Domain, Skill, Strategy


class DomainListView(ListView):
    model = Domain
    context_object_name = 'domains'
    template_name = 'domain/domains.html'


class DomainDetailView(DetailView):
    model = Domain
    context_object_name = 'domain'
    template_name = 'domain/domain_detail.html'

    def get_object(self):
        return get_object_or_404(Domain, code=self.kwargs['domain_code'])


class DomainCreateView(CreateView):
    model = Domain
    fields = ['name', 'description']
    template_name = 'domain/domain_create.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy("domain_detail", args=(self.object.code,))


class DomainUpdateView(UpdateView):
    model = Domain
    fields = ['name', 'description']
    context_object_name = 'domain'
    template_name = 'domain/domain_update.html'

    def get_object(self):
        return get_object_or_404(Domain, code=self.kwargs['domain_code'])

    def get_success_url(self, **kwargs):
        return reverse_lazy("domain_detail", args=(self.object.code,))


class SkillCreateView(CreateView):
    model = Skill
    fields = ['domain', 'name', 'description']
    template_name = 'domain/skill_create.html'

    def get_initial(self):
        initial = super(SkillCreateView, self).get_initial()
        initial['domain'] = get_object_or_404(Domain, code=self.kwargs['domain_code'])
        return initial

    def get_success_url(self, **kwargs):
        return reverse_lazy("skill_detail", args=(self.object.domain.code, self.object.code,))


class SkillDetailView(DetailView):
    model = Skill
    context_object_name = 'skill'
    template_name = 'domain/skill_detail.html'

    def get_object(self):
        domain = get_object_or_404(Domain, code=self.kwargs['domain_code'])
        return get_object_or_404(Skill, domain=domain, code=self.kwargs['skill_code'])


class SkillUpdateView(UpdateView):
    model = Skill
    fields = ['name', 'description']
    context_object_name = 'skill'
    template_name = 'domain/skill_update.html'

    def get_object(self):
        domain = get_object_or_404(Domain, code=self.kwargs['domain_code'])
        return get_object_or_404(Skill, domain=domain, code=self.kwargs['skill_code'])

    def get_success_url(self, **kwargs):
        return reverse_lazy("skill_detail", args=(self.object.domain.code, self.object.code,))


class StrategyCreateView(CreateView):
    model = Strategy
    fields = ['skill_goal', 'name', 'problem']
    template_name = 'domain/strategy_create.html'

    def get_initial(self):
        initial = super(StrategyCreateView, self).get_initial()
        domain = get_object_or_404(Domain, code=self.kwargs['domain_code'])
        initial['skill_goal'] = get_object_or_404(Skill, domain=domain, code=self.kwargs['skill_code'])
        return initial

    def get_success_url(self, **kwargs):
        return reverse_lazy("strategy_update", args=(self.object.skill_goal.domain.code,
                                                     self.object.skill_goal.code,
                                                     self.object.code,))


class StrategyDetailView(DetailView):
    model = Strategy
    context_object_name = 'strategy'
    template_name = 'domain/strategy_detail.html'

    def get_object(self):
        domain = get_object_or_404(Domain, code=self.kwargs['domain_code'])
        skill = get_object_or_404(Skill, domain=domain, code=self.kwargs['skill_code'])
        return get_object_or_404(Strategy, skill_goal=skill, code=self.kwargs['strategy_code'])


class StrategyUpdateView(UpdateView):
    model = Strategy
    context_object_name = 'strategy'
    fields = ['skill_goal', 'name', 'problem']
    template_name = 'domain/strategy_actions_update.html'

    def get_object(self):
        domain = get_object_or_404(Domain, code=self.kwargs['domain_code'])
        skill = get_object_or_404(Skill, domain=domain, code=self.kwargs['skill_code'])
        return get_object_or_404(Strategy, skill_goal=skill, code=self.kwargs['strategy_code'])

    def get_success_url(self, **kwargs):
        return reverse_lazy("strategy_update", args=(self.object.skill_goal.domain.code,
                                                     self.object.skill_goal.code,
                                                     self.object.code,))

    #    def get_form_kwargs(self):
    #        kwargs = super(StrategyUpdateView, self).get_form_kwargs()
    #        kwargs.update({
    #            'domain_code': self.kwargs['domain_code']
    #        })
    #        return kwargs

    def get_context_data(self, **kwargs):
        context = super(StrategyUpdateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = ActionsFormSet(self.request.POST, instance=self.object,
                                                form_kwargs={'domain_code': self.object.skill_goal.domain.code})
            context['formset'].full_clean()
        else:
            context['formset'] = ActionsFormSet(instance=self.object,
                                                form_kwargs={'domain_code': self.object.skill_goal.domain.code})
            print(context['formset'])
        return context

    def form_valid(self, form):
        context = self.get_context_data(form=form)
        formset = context['formset']
        if formset.is_valid():
            response = super().form_valid(form)
            formset.instance = self.object
            formset.save()
            return response
        else:
            return super().form_invalid(form)

templates/domain/domain_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>Add Domain</h2>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success"> Add </button>
</form>
{% endblock %}

templates/domain/domain_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
    <a href="{% url 'domain_update' domain.code %}"
       class="btn btn-primary"> Update </a>
    <a href="{% url 'skill_create' domain.code %}" class="btn btn-primary"> Add Skill </a>
    <div class="container">
        <table class="table table-borderless">
            <tbody>
            <tr>
                <th class="col-2"> code</th>
                <td class="col-10"> {{ domain.code }}</td>
            </tr>
            <tr>
                <th> name</th>
                <td> {{ domain.name }}</td>
            </tr>
            <tr>
                <th> description</th>
                <td> {{ domain.description }}</td>
            </tr>
            </tbody>
        </table>
    </div>

    <div>
        <table class="table table-hover">
            <thead>
            <tr>
                <th> code</th>
                <th> name</th>
                <th> description</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for skill in domain.skill_set.all %}
                <tr>
                    <td>{{ skill.code }}</td>
                    <td>{{ skill.name }}</td>
                    <td>{{ skill.description }}</td>
                    <td><a href="{% url 'skill_detail' domain.code skill.code %}" class="btn btn-info"> Skill Detail </a>
                        <a href="{% url 'skill_update' domain.code skill.code %}" class="btn btn-info"> Skill Update </a></td>
                </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
{% endblock %}

templates/domain/domain_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>Update Domain</h2>
    <a href="{% url 'domain_detail' form.instance.code %}"
       class="btn btn-primary"> Back to domain </a>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success"> Update </button>
</form>
{% endblock %}

templates/domain/domains.html
{% extends "base.html" %}

{% block content %}
    <h2>Domains List</h2>
    <div><a href="{% url 'domain_create' %}" class="btn btn-primary"> Add </a></div>

    <table class="table table-hover">
        <thead>
        <tr>
            <th> code</th>
            <th> name</th>
            <th> description</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for domain in domains %}
            <tr>
                <td>{{ domain.code }}</td>
                <td>{{ domain.name }}</td>
                <td>{{ domain.description }}</td>
                <td><a href="{% url 'domain_detail' domain.code %}" class="btn btn-info"> Domain Detail </a>
                    <a href="{% url 'domain_update' domain.code %}" class="btn btn-info"> Domain Update </a></td>
            </tr>
        {% endfor %}
        </tbody>

    </table>
{% endblock %}

templates/domain/skill_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>Add Skill</h2>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success"> Add </button>
</form>
{% endblock %}

templates/domain/skill_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
    <a href="{% url 'domain_detail' skill.domain.code %}"
       class="btn btn-primary"> Back to domain </a>
    <a href="{% url 'skill_update' skill.domain.code skill.code %}"
       class="btn btn-primary"> Update </a>
    <a href="{% url 'strategy_create' skill.domain.code skill.code %}" class="btn btn-primary"> Add Strategy </a>
    <div class="container">
        <table class="table table-borderless">
            <tbody>
            <tr>
                <th class="col-2"> domain</th>
                <td class="col-10"> <a href="{% url 'domain_detail' skill.domain.code %}" class="btn btn-primary"> {{ domain }} </a></td>
            </tr>
            <tr>
                <th> code</th>
                <td> {{ skill.code }}</td>
            </tr>
            <tr>
                <th> name</th>
                <td> {{ skill.name }}</td>
            </tr>
            <tr>
                <th> description</th>
                <td> {{ skill.description }}</td>
            </tr>
            </tbody>
        </table>
    </div>

    <div>
        <table class="table table-hover">
            <thead>
            <tr>
                <th> code</th>
                <th> name</th>
                <th> problem</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for strategy in skill.strategy_set.all %}
                <tr>
                    <td>{{ strategy.code }}</td>
                    <td>{{ strategy.name }}</td>
                    <td>{{ strategy.description }}</td>
                    <td><a href="{% url 'strategy_detail' skill.domain.code skill.code strategy.code %}"
                           class="btn btn-info"> Strategy Detail </a>
                        <a href="{% url 'strategy_update' skill.domain.code skill.code strategy.code %}"
                           class="btn btn-info"> Strategy Update </a></td>
                </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
{% endblock %}

templates/domain/skill_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>Update Skill</h2>
    <a href="{% url 'domain_detail' form.instance.domain.code %}"
       class="btn btn-primary"> Back to domain </a>
    <a href="{% url 'skill_detail' form.instance.domain.code form.instance.code %}"
       class="btn btn-primary"> Back to skill </a>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success"> Add </button>
</form>
{% endblock %}

templates/domain/strategy_actions_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h2>Update Strategy</h2>
    <a href="{% url 'domain_detail' form.instance.skill_goal.domain.code %}"
       class="btn btn-primary"> Back to domain </a>
    <a href="{% url 'skill_detail' form.instance.skill_goal.domain.code form.instance.skill_goal.code %}"
       class="btn btn-primary"> Back to skill </a>
    <a href="{% url 'strategy_detail' form.instance.skill_goal.domain.code form.instance.skill_goal.code form.instance.code %}"
       class="btn btn-primary"> Back to strategy </a>
    <form method="post">
        {{ formset.management_form|crispy }}
        {% csrf_token %}
        {{ form|crispy }}

        <table class="table table-sm">
            <thead>
            <tr>
                <th> order</th>
                <th> description</th>
                <th> prerequisites</th>
                <th> Удалить?</th>
            </tr>
            </thead>
            <tbody>
            {% for action_form in formset %}
                {% if action_form.errors %}
                    <tr>
                        <td> {% for e in action_form.non_field_errors %} {{ e }} {% endfor %}</td>
                    </tr>
                {% endif %}
                <tr>
                    {% for field in action_form %}
                        {% include 'bootstrap/field.html' with tag="td" form_show_labels=False %}
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <button type="submit" class="btn btn-success"> Add</button>
    </form>
{% endblock %}

templates/domain/strategy_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>Add Strategy</h2>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success"> Add </button>
</form>
{% endblock %}

templates/domain/strategy_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
    <a href="{% url 'domain_detail' strategy.skill_goal.domain.code %}"
       class="btn btn-primary"> Back to domain </a>
    <a href="{% url 'skill_detail' strategy.skill_goal.domain.code strategy.skill_goal.code %}"
       class="btn btn-primary"> Back to skill </a>
    <a href="{% url 'strategy_update' strategy.skill_goal.domain.code strategy.skill_goal.code strategy.code %}"
       class="btn btn-primary"> Update </a>
    <div class="container">
        <table class="table table-borderless">
            <tbody>
            <tr>
                <th class="col-2"> domain</th>
                <td class="col-10"><a href="{% url 'domain_detail' strategy.skill_goal.domain.code %}"
                                      class="btn btn-primary"> {{ strategy.skill_goal.domain }} </a></td>
            </tr>
            <tr>
                <th> skill</th>
                <td><a href="{% url 'skill_detail' strategy.skill_goal.domain.code strategy.skill_goal.code %}"
                       class="btn btn-primary"> {{ strategy.skill_goal }} </a></td>
            </tr>
            <tr>
                <th> code</th>
                <td> {{ strategy.code }}</td>
            </tr>
            <tr>
                <th> name</th>
                <td> {{ strategy.name }}</td>
            </tr>
            <tr>
                <th> problem </th>
                <td> {{ strategy.problem }}</td>
            </tr>
        </tbody>
    </table>

        <table class="table table-sm">
            <thead>
            <tr>
                <th> order</th>
                <th> description</th>
                <th> prerequisites</th>
            </tr>
            </thead>
            <tbody>

            {% for action in strategy.action_set.all %}
                <tr>
                    <td> {{ action.order }} </td>
                    <td> {{ action.description }} </td>
                    <td>
                        {% for prereq in action.prerequisites.all %}
                            <div class="container mt-2"><a
                                    href="{% url 'strategy_detail' prereq.skill_goal.domain.code prereq.skill_goal.code prereq.code %}"
                                    class="btn btn-primary"> {{ prereq }} </a></div>
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}